[package]
name = "hyperlight_guest_capi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude = ["/include"]

[lib]
crate-type = ["staticlib"]

[lints]
workspace = true

[features]
default = ["guest_time"]
# Enable paravirtualized clock support for guest time functions
guest_time = ["hyperlight-guest/guest_time", "hyperlight-guest-bin/guest_time"]

[dependencies]
hyperlight-guest = { workspace = true, default-features = false }
hyperlight-guest-bin = { workspace = true, default-features = true }
hyperlight-common = { workspace = true, default-features = false }

flatbuffers = { version = "25.12.19", default-features = false }
log = { version = "0.4", default-features = false }

[build-dependencies]
cbindgen = "0.29.2"
