# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Guest Binaries

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  contents: read
  
jobs:
  # this job has no dependencies
  build-guest-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build: [hyperlight-kvm-debug, hyperlight-kvm-release]
        include:
          - build: hyperlight-kvm-debug
            os: hyperlight-kvm
            config: debug
          - build: hyperlight-kvm-release
            os: hyperlight-kvm
            config: release

    steps:
      - uses: actions/checkout@v6

      - uses: hyperlight-dev/ci-setup-workflow@v1.8.0
        with:
          rust-toolchain: "1.89"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and move Rust and C guests
        run: just guests

      - name: Upload Rust Guest Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: rust-guest-binaries-${{ matrix.config }}
          path: |
            src\tests\rust_guests\bin\${{ matrix.config }}\dummyguest
            src\tests\rust_guests\bin\${{ matrix.config }}\simpleguest
          if-no-files-found: error

      - name: Upload C Guest Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: c-guest-binaries-${{ matrix.config }}
          path: |
            src\tests\c_guests\bin\${{ matrix.config }}\simpleguest
          if-no-files-found: error
